language: nix
script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use musteresel
  - if [ -n "$CACHIX_SIGNING_KEY" ]; then (cd utils/pandoc-project-relative-links; nix-build --no-out-link | cachix push musteresel); fi
  - nix-shell shell.nix --run make
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  commit_message: "Build output of $TRAVIS_COMMIT"
  local_dir: build
  target_branch: master
  on:
    branch: sources-master
