language: nix
script:
  - nix-shell shell.nix --run make
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  commit_message: "Build output of $TRAVIS_COMMIT"
  local_dir: build
  target_branch: master
  on:
    branch: sources-master
