name: "Build and deploy to master branch"
on: push
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Build site using nix and Makefile
      id: build
      run: nix-shell --run "make && echo OK"
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/
  deploy:
    runs-on: ubuntu-latest
    needs: build-site
    if: github.ref == 'refs/heads/sources-master'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - uses: actions/download-artifact@v4
      with:
        name: github-pages
    - name: Extract artifact from build
      run: tar -xaf artifact.tar
    - name: Remove artifact archive
      run: rm artifact.tar
    - name: Create a new commit and push it
      run: |
        git config --global user.name "Daniel Jour"
        git config --global user.email "musteresel@users.noreply.github.com"
        git diff
        git add . 
        git status
        git commit -m "Automatic deploy at $(TZ=":Europe/Berlin" date)"
        git push
